### ISSUE TITLE
Because every version of flutter_test from sdk depends on quiver 2.0.5 and flutter_whirlpool depends on quiver 2.1.3, flutter_test from sdk is forbidden.

### ISSUE THREAD

**Issue by jwxiaoming** [pawlik92/flutter_whirlpool#3]
[flutter_whirlpool] flutter pub get
Running "flutter pub get" in flutter_whirlpool...               
Because every version of flutter_test from sdk depends on quiver 2.0.5 and flutter_whirlpool depends on quiver 2.1.3, flutter_test from sdk is forbidden.

So, because flutter_whirlpool depends on flutter_test any from sdk, version solving failed.
pub get failed (1; So, because flutter_whirlpool depends on flutter_test any from sdk, version solving failed.)
exit code 1

**Comment by pawlik92** [comment]
What version of flutter do you have?
This app needs Flutter 1.17+. And your error sounds like you have something below.

**Comment by jwxiaoming** [comment]
Why is the particle scrolling effect stuck on the ios simulator? Works fine on Android devices, but there are still noticeable dropped frames

**Comment by pawlik92** [comment]
Physics simulation needs more power than a regular application. It's hard for me to answer your question. If you have run applications on an for example iPhone 11 max emulator, and on Android with a much lower resolution, I'm not surprised that there are drops on iPhone emu.  You didn't give enough details. The emulator needs good hardware to make it behave like a real device. 

Please, describe one problem per issue and always provide more details. 
If you can run Flutter project then I will close this issue.
