### ISSUE TITLE
Hello, very like your app, is very good. I met a bug, the app can display normal, but can't see the water, also can't see the water in the rotation, to quote the following error:

### ISSUE THREAD

**Issue by guolidaxian** [pawlik92/flutter_whirlpool#5]
Hello, very like your app, is very good. I met a bug, the app can display normal, but can't see the water, also can't see the water in the rotation, to quote the following error:

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
RenderBox was not laid out: RenderClipOval#2745f
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1930 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

**Comment by whoitao** [comment]
Hello:

You just need to add the following code in _WhirlpoolRenderObject which located in lib/screens/main/washing_machine/drum/washing_machine_drum.dart.

> @override
  Size computeDryLayout(BoxConstraints constraints) {
     return constraints.biggest;
  }

The Reason: https://flutter.dev/docs/release/breaking-changes/renderbox-dry-layout

**Comment by guolidaxian** [comment]
> Hello:
> 
> You just need to add the following code in _WhirlpoolRenderObject which located in lib/screens/main/washing_machine/drum/washing_machine_drum.dart.
> 
> > @OverRide
> > Size computeDryLayout(BoxConstraints constraints) {
> > return constraints.biggest;
> > }
> 
> The Reason: https://flutter.dev/docs/release/breaking-changes/renderbox-dry-layout

问题已经按您的指点解决！！谢谢！非常感谢！（Problems have been solved according to your advice!! Thank you very much! Thank you very much!
）
