### ISSUE TITLE
Need Permission for production Ready app

### ISSUE THREAD

**Issue by Manishmg3994** [pawlik92/flutter_whirlpool#6]
Dear Sir I like your washing machine flutter design and wish to get it in production ,i wish you to give me content permission

**Comment by pawlik92** [comment]
Hello,
This project was created to demonstrate the possibilities that flutter offers. The whole UI design was drawn by Dimest and thanks to his kindness I was able to use it in this project.
You are free to use technical aspects of this project, but unfortunately I can't decide if it can be used in such a form in production- I don't have ownership rights to the graphic design, on which the application was based.

**Comment by Manishmg3994** [comment]
Dimest is super cool designer ,and if you don't have ownership rights to the graphic design then you can suggest me the graphic designer name so  that i can ask him/her . For case of production level i will do  changements and give it a better look and also custom backend the main reason for adopting this design was its super cool UI and i wish you can make me learn about those kind of animation (wishing you will share these type of awesome source code <public> in your repo>
